server:
  port: 9091
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/parking
    username: lch
    password: qwer123!
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  
logging:
  level:
    root: INFO
    com.school.demo: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    path: /var/log/myapp
    name: myapp.log
    max-size: 10MB
    max-history: 7
